version: '1.0'

services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - web-auth
      - model-services
      - patient-services

  web-auth:
    build: ./web-auth
    ports:
      - "3001:3001"
  
  model-services:
    build: ./model-services
    ports:
      - "3002:3002"
  
  patient-services:
    build: ./patient-services
    ports:
      - "3003:3003"