FROM python:latest

WORKDIR /web-auth

COPY . .

EXPOSE 3001

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3001"]